
defaults:
  - _self_


num_models: 3
num_parallel_envs: 4 # NOTE: log freqs have to be divisible by num_parallel_envs 
train_interval: 4000000
num_eval_eps: 10
verbose: true
video_length: 200
video_log_freq: 20000
reward_log_freq: 1000
save_weight_freq: 50000
wandb_log: false

auxiliary_loss:
  - train_every: 1000
  - batch_size: 256
  - aux_loss_updates: 2

method: "visual"
# options: visual, expert, barlow-twins, factored-graph, supervised, factored-vf, dreamerv2, ssl-cov-ik, ssl-mask-reconst
algorithm: "a2c"
# options: ppo, a2c, sac
obs_encoder:
  encoder: "impala-large" # options: [for images -- impala-large, impala-small, nature; for vector -- mlp]
  enable_rssm: false

representation_vector:
  observation_encoder_dim: 256
  num_factors: 64
  vector_size_per_factor: 4

projection_architecture: [128, 128]

ppo_configs:
  normalize: true

  ppo_architecture:
    pi_dims: [64, 128, 256]
    vf_dims: [64, 128, 256]
  n_steps: 200
  n_epochs: 10
  learning_rate: 0.0003
  batch_size: 400
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.15
  clip_range_vf: 0.65
  normalize_advantage: True
  ent_coef: 0.01
  max_grad_norm: 0.5
  target_kl: null
  verbose: null
  seed: null

dv2_configs:
  test: false